// App-wide
export const APP_LOAD = 'APP_LOAD';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// Authentication
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_SUCCESS'

export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS'
export const USER_SIGN_OUT_FAILURE = 'USER_SIGN_OUT_SUCCESS'

// Journal
export const FETCH_JOURNALS_REQUEST = 'FETCH_JOURNALS_REQUEST';
export const FETCH_JOURNALS_SUCCESS = 'FETCH_JOURNAL_SUCCESSS';
export const FETCH_JOURNALS_FAILURE = 'FETCH_JOURNALS_FAILURE';

export const CREATE_JOURNAL_REQUEST = 'CREATE_JOURNAL_REQUEST';
export const CREATE_JOURNAL_SUCCESS = 'CREATE_JOURNAL_SUCCESS';
export const CREATE_JOURNAL_FAILURE = 'CREATE_JOURNAL_FAILURE';

export const MODIFY_JOURNAL_REQUEST = 'MODIFY_JOURNAL_REQUEST';
export const MODIFY_JOURNAL_SUCCESS = 'MODIFY_JOURNAL_SUCCESS';
export const MODIFY_JOURNAL_FAILURE = 'MODIFY_JOURNAL_FAILURE';

export const DELETE_JOURNAL_REQUEST = 'DELETE_JOURNAL_REQUEST';
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS';
export const DELETE_JOURNAL_FAILURE = 'DELETE_JOURNAL_FAILURE';

export const SET_ACTIVE_JOURNAL = 'SET_ACTIVE_JOURNAL';

// Trade
export const FETCH_TRADES_REQUEST = 'FETCH_TRADES_REQUEST';
export const FETCH_TRADES_SUCCESS = 'FETCH_TRADES_SUCCESS';
export const FETCH_TRADES_FAILURE = 'FETCH_TRADES_FAILURE';

export const CREATE_TRADE_REQUEST = 'CREATE_TRADE_REQUEST';
export const CREATE_TRADE_SUCCESS = 'CREATE_TRADE_SUCCESS';
export const CREATE_TRADE_FAILURE = 'CREATE_TRADE_FAILURE';

export const MODIFY_TRADE_REQUEST = 'MODIFY_TRADE_REQUEST';
export const MODIFY_TRADE_SUCCESS = 'MODIFY_TRADE_SUCCESS';
export const MODIFY_TRADE_FAILURE = 'MODIFY_TRADE_FAILURE';

export const DELETE_TRADE_REQUEST = 'DELETE_TRADE_REQUEST';
export const DELETE_TRADE_SUCCESS = 'DELETE_TRADE_SUCCESS';
export const DELETE_TRADE_FAILURE = 'DELETE_TRADE_FAILURE';

export const CLEAR_TRADES = 'CLEAR_TRADES';
export const SET_TRADE_FILTERS = 'SET_TRADE_FILTERS';