// App-wide
export const APP_LOAD = 'APP_LOAD';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// Authentication
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS'
export const USER_SIGN_OUT_FAILURE = 'USER_SIGN_OUT_SUCCESS'

// Journal
export const FETCH_JOURNALS = 'FETCH_JOURNALS';
export const CREATE_JOURNAL = 'CREATE_JOURNAL';
export const MODIFY_JOURNAL = 'MODIFY_JOURNAL';
export const DELETE_JOURNAL = 'DELETE_JOURNAL';
export const SET_ACTIVE_JOURNAL = 'SET_ACTIVE_JOURNAL';
export const FETCH_TRADES = 'FETCH_TRADES';
export const CREATE_TRADE = 'CREATE_TRADE';
export const CLEAR_TRADES = 'CLEAR_TRADES';
export const MODIFY_TRADE = 'MODIFY_TRADE';
export const DELETE_TRADE = 'DELETE_TRADE';
export const SET_TRADE_FILTERS = 'SET_TRADE_FILTERS';